typeidea/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from blog.views import (
    IndexView, CategoryView, TagView, PostDetailView, SearchView, AuthorView
)
from comment.views import CommentView
from config.views import LinkListView
from .custom_site import custom_site

urlpatterns = [
    re_path(r'^$', IndexView.as_view(), name='index'),
    re_path(r'^category/(?P<category_id>\d+)/$', CategoryView.as_view(), name='category-list'),
    re_path(r'^tag/(?P<tag_id>\d+)/$', TagView.as_view(), name='tag-list'),
    re_path(r'^post/(?P<post_id>\d+).html$', PostDetailView.as_view(), name='post-detail'),
    re_path(r'^search/$', SearchView.as_view(), name='search'),
    re_path(r'^author/(?P<owner_id>\d+)/$', AuthorView.as_view(), name='author'),
    re_path(r'links/$', LinkListView.as_view(), name='links'),
    re_path(r'comment/$', CommentView.as_view(), name='comment'),
    path('admin/', admin.site.urls, name='admin'),
    path('super_admin/', custom_site.urls, name='super_admin'),
]

from typeidea.settings import develop

if develop.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      re_path(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

comment/models.py
from django.db import models


# Create your models here.
# 评论模型
class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )

    target = models.CharField(max_length=100, verbose_name="评论目标")
    content = models.CharField(max_length=2000, verbose_name="内容")
    nickname = models.CharField(max_length=50, verbose_name="昵称")
    website = models.URLField(verbose_name="网站")
    email = models.EmailField(verbose_name="邮箱")
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = verbose_name_plural = '评论'

    def __str__(self):
        return self.target

    @classmethod
    def get_by_target(cls, target):
        return cls.objects.filter(target=target, status=cls.STATUS_NORMAL)

comment/forms.py
from django import forms
import mistune

from .models import Comment


class CommentForm(forms.ModelForm):
    nickname = forms.CharField(
        label='昵称',
        max_length=50,
        widget=forms.widgets.Input(
            attrs={
                'class': 'form-control',
                'style': "width:60%;"
            }
        )
    )

    email = forms.CharField(
        label='Email',
        max_length=50,
        widget=forms.widgets.EmailInput(
            attrs={
                'class': 'form-control',
                'style': "width:60%;"
            }
        )
    )

    website = forms.CharField(
        label='网站',
        max_length=100,
        widget=forms.widgets.URLInput(
            attrs={
                'class': 'form-control',
                'style': "width:60%;"
            }
        )
    )

    content = forms.CharField(
        label='内容',
        max_length=500,
        widget=forms.widgets.Textarea(
            attrs={
                'class': 'form-control',
                'rows': '6',
                'cols': 60
            }
        )
    )

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if len(content) < 10:
            raise forms.ValidationError('内容长度怎么能这么短呢!')
        content = mistune.markdown(content)
        return content

    class Meta:
        model = Comment
        fields = ['nickname', 'email', 'website', 'content']

comment/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView

from .forms import CommentForm


# Create your views here.


class CommentView(TemplateView):
    http_method_names = ['post']
    template_name = 'comment/result.html'

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        target = request.POST.get('target')

        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.target = target
            instance.save()
            succeed = True
            return redirect(target)
        else:
            succeed = False

        context = {
            'succeed': succeed,
            'form': comment_form,
            'target': target
        }

        return self.render_to_response(context)

typeidea/themes/bootstrap/templates/comment/block.html
{% extends 'blog/base.html' %}

{% block title %}{{ post.title }} {% endblock %}

{% block main %}
    {% if post %}
        <div class="card-body">
            <h1 class="card-title"><a href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h1>
            <span class="card-link">作者:<a href="#">{{ post.owner.username }}</a></span>
            <span class="card-link">分类:<a
                    href="{% url 'category-list' post.category.id %}">{{ post.category.name }}</a></span>
        </div>
        <hr>
        <p class="card-text">{{ post.content }}</p>
    {% endif %}
{% endblock %}

<hr/>

<div class="comment">
    <form action="/comment/" class="form-group" method="POST">
        {% csrf_token %}
        <input name="target" type="hidden" value="{{ target }}"/>
        {{ comment_form }}
        <input type="submit" value="写好了!"/>
    </form>

    <ul class="list-group">
        {% for comment in comment_list %}
            <li class="list-group-item">
                <div class="nickname">
                    <a href="{{ comment.website }}">{{ comment.nickname }}</a>
                    <span>{{ comment.created_name }}</span>
                </div>
                <div class="comment-content">
                    {% autoescape off %}
                    {{ comment.content }}
                    {% endautoescape %}
                </div>
            </li>
        {% endfor %}
    </ul>
</div>

typeidea/themes/bootstrap/templates/comment/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>评论结果页</title>
    <style>
        body {
            TEXT-ALIGN: center;
        }

        .result {
            text-align: center;
            width: 40%;
            margin: auto;
        }

        .errorlist {
            color: red;
        }

        ul li {
            list-style-type: None;
        }
    </style>
</head>
<body>
<div class="result">
    {% if succeed %}
        评论成功
        <a href="{{ target }}">返回</a>
    {% else %}
        <ul class="errorlist">
            {% for field,message in form.errors.items %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
        <a href="javascript:window.history.back();">返回</a>
    {% endif %}
</div>
</body>
</html>